# Generated by Django 4.1.5 on 2023-01-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Workout date')),
                ('body', models.CharField(choices=[('B', 'Back and Chest'), ('L', 'Legs'), ('A', 'Arms')], default='B', max_length=1)),
            ],
        ),
    ]
