# Generated by Django 4.1.4 on 2023-01-09 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_workout_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 9), verbose_name='Workout date'),
        ),
    ]
