# Generated by Django 4.1.4 on 2023-01-11 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
    ]
