# Generated by Django 4.1.4 on 2023-01-12 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 12), verbose_name='Workout date'),
        ),
    ]
