# Generated by Django 4.1.5 on 2023-01-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='grams',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine',
            name='reps',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine',
            name='sets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
