# Generated by Django 4.2.16 on 2026-06-14 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_diet_grams_routine_reps_routine_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Workout date'),
        ),
    ]
